// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Course struct {
	ID          string           `json:"id"`
	TeacherID   string           `json:"teacher_id"`
	Title       string           `json:"title"`
	Description pgtype.Text      `json:"description"`
	Thumbnail   pgtype.Text      `json:"thumbnail"`
	Duration    int32            `json:"duration"`
	Domain      string           `json:"domain"`
	Rating      pgtype.Numeric   `json:"rating"`
	Level       string           `json:"level"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
	UpdatedAt   pgtype.Timestamp `json:"updated_at"`
}

type CourseTag struct {
	CourseID string `json:"course_id"`
	Tag      string `json:"tag"`
}

type Enrollment struct {
	ID                       string           `json:"id"`
	UserID                   string           `json:"user_id"`
	CourseID                 string           `json:"course_id"`
	EnrolledAt               pgtype.Timestamp `json:"enrolled_at"`
	StartedAt                pgtype.Timestamp `json:"started_at"`
	CompletedAt              pgtype.Timestamp `json:"completed_at"`
	CourseProgressPercentage pgtype.Numeric   `json:"course_progress_percentage"`
	CourseProgressStatus     string           `json:"course_progress_status"`
	CreatedAt                pgtype.Timestamp `json:"created_at"`
	UpdatedAt                pgtype.Timestamp `json:"updated_at"`
}

type Exercise struct {
	ID            string           `json:"id"`
	LessonID      string           `json:"lesson_id"`
	Question      string           `json:"question"`
	Answers       []string         `json:"answers"`
	CorrectAnswer string           `json:"correct_answer"`
	OrderIndex    int32            `json:"order_index"`
	CreatedAt     pgtype.Timestamp `json:"created_at"`
	UpdatedAt     pgtype.Timestamp `json:"updated_at"`
}

type Lesson struct {
	ID         string           `json:"id"`
	ModuleID   string           `json:"module_id"`
	Title      string           `json:"title"`
	Overview   pgtype.Text      `json:"overview"`
	Content    pgtype.Text      `json:"content"`
	VideoID    pgtype.Text      `json:"video_id"`
	OrderIndex int32            `json:"order_index"`
	CreatedAt  pgtype.Timestamp `json:"created_at"`
	UpdatedAt  pgtype.Timestamp `json:"updated_at"`
}

type LessonProgress struct {
	EnrollmentID       string           `json:"enrollment_id"`
	LessonID           string           `json:"lesson_id"`
	ProgressPercentage pgtype.Numeric   `json:"progress_percentage"`
	ProgressStatus     string           `json:"progress_status"`
	ExerciseScore      pgtype.Numeric   `json:"exercise_score"`
	CreatedAt          pgtype.Timestamp `json:"created_at"`
	UpdatedAt          pgtype.Timestamp `json:"updated_at"`
}

type Module struct {
	ID         string           `json:"id"`
	CourseID   string           `json:"course_id"`
	Title      string           `json:"title"`
	OrderIndex int32            `json:"order_index"`
	CreatedAt  pgtype.Timestamp `json:"created_at"`
	UpdatedAt  pgtype.Timestamp `json:"updated_at"`
}

type ModuleProgress struct {
	EnrollmentID       string           `json:"enrollment_id"`
	ModuleID           string           `json:"module_id"`
	ProgressPercentage pgtype.Numeric   `json:"progress_percentage"`
	ProgressStatus     string           `json:"progress_status"`
	CreatedAt          pgtype.Timestamp `json:"created_at"`
	UpdatedAt          pgtype.Timestamp `json:"updated_at"`
}

type User struct {
	ID        string           `json:"id"`
	Username  string           `json:"username"`
	Email     string           `json:"email"`
	Role      string           `json:"role"`
	Profile   pgtype.Text      `json:"profile"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	UpdatedAt pgtype.Timestamp `json:"updated_at"`
}
